version: '3'
services:
  jekyll-test:
    image: jekyll/jekyll:latest
    platform: linux/amd64
    volumes:
      - ./src:/srv/jekyll
    working_dir: /srv/jekyll
    ports:
      - "4000:4000"
      - "35729:35729"
    command: sh -c "bundle install && gem install webrick && jekyll serve --verbose --trace --livereload"
    # command: jekyll serve --host --verbose --trace
