name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      - name: Checkout working directory
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: for-gh-pages

      - name: Deploy
        run: |
            cd for-gh-pages
            git rm -r --ignore-unmatch *
            rm -f .gitignore
            rm -rf .github
            ls -la ../docs
            cp -R ../docs/_pages/* .
            cp -R ../docs/*.md .
            touch .nojekyll
            git add --all
            git config --global user.name '${{github.actor}}'
            git config --global user.email '${{github.actor}}@users.noreply.github.com'
            git commit -m "deploy ${{github.sha}}"
            git push origin gh-pages